# Jekyll configuration
markdown: redcarpet
permalink: posts/:title
baseurl:

# feed.atom configuration
name: Constituyente Chile
url: http://constituyentechile.cl
description: "Somos chilenas y chilenos decididos a ejercer efectivamente el derecho a determinar nuestro propio destino como pueblo y como naci√≥n."
author: Constituyente Chile
keywords: "asamblea, asamblea constituyente, constituyente chile, asamblea constiturente chile"

disqus:
  shortname: asambleaconstituyente

twitter:
  username: '@AConstituyenteC'

google:
  analytics: 'UA-53620410-1'

collections:
  documents:
    output: true
  flyers:
    output: true
  presentations:
    output: true